/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eebbk_behavior_demo_utils_JNIUtils */

#ifndef _Included_com_eebbk_behavior_demo_utils_JNIUtils
#define _Included_com_eebbk_behavior_demo_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eebbk_behavior_demo_utils_JNIUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eebbk_behavior_demo_utils_JNIUtils_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
